[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "payment-ledger-api"
version = "0.1.0"
description = "Async REST API for users, accounts and payment webhooks"
requires-python = ">=3.11,<3.12"
dependencies = [
    "python-dotenv",
    "sanic",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "sanic-testing"
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.pytest.ini_options]
testpaths = ["tests"]
